from __future__ import annotations

from typing import Any, Protocol


class RosBackend(Protocol):
    name: str

    def doctor(self) -> dict[str, Any]: ...
    def list_topics(self) -> list[dict[str, Any]]: ...
    def topic_info(self, topic: str) -> dict[str, Any]: ...
    def topic_echo(self, topic: str, count: int = 1) -> list[dict[str, Any]]: ...
    def topic_pub(
        self,
        topic: str,
        msg_type: str,
        data: dict[str, Any],
        times: int = 1,
    ) -> dict[str, Any]: ...
    def list_nodes(self) -> list[str]: ...
    def node_info(self, node: str) -> dict[str, Any]: ...
    def list_services(self) -> list[dict[str, Any]]: ...
    def service_call(
        self,
        service: str,
        srv_type: str,
        request: dict[str, Any],
    ) -> dict[str, Any]: ...
    def list_params(self, node: str | None = None) -> list[dict[str, Any]]: ...
    def get_param(self, node: str, name: str) -> dict[str, Any]: ...
    def set_param(self, node: str, name: str, value: Any) -> dict[str, Any]: ...
    def graph_summary(self) -> dict[str, Any]: ...
    def seed_demo(self) -> dict[str, Any]: ...
    def tf_tree(self) -> dict[str, Any]: ...
    def list_actions(self) -> list[dict[str, Any]]: ...
    def action_send_goal(
        self,
        action: str,
        action_type: str,
        goal: dict[str, Any],
    ) -> dict[str, Any]: ...
